# Generated by Django 3.2.3 on 2021-11-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.IntegerField(null=True),
        ),
    ]
