# Generated by Django 3.2.3 on 2021-11-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
