# Generated by Django 3.2.3 on 2021-11-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_genre_genre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
