# Generated by Django 3.2.3 on 2021-11-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20211120_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
    ]
