# Generated by Django 3.2.3 on 2021-11-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movie_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(unique=True),
        ),
    ]
