# Generated by Django 3.2.3 on 2021-11-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.ManyToManyField(related_name='movies', to='movies.Keyword'),
        ),
    ]
