# Generated by Django 3.2.3 on 2021-11-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_alter_movie_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop_path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
